### ISSUE TITLE
Create a sandbox account on GCP

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#126]
# Summary

It would be helpful to have our own Google Cloud space to prototype infrastructure and deployments. This would allow us to experiment on our own resources, which would give us more flexibility in what we try out.

# Acceptance criteria

We have a space on GCP, accessible to everyone on the @2i2c-org/tech-team, where we can deploy GCP-related infrastructure.

# Tasks to complete

- [x] Figure out how to set up a project in GCP that we all have access to
- [x] Decide on who will pay the bill for this infrastructure
- [x] #137
- [x] #140

**Comment by damianavila** [comment]
AFAIK, we currently own a GCP space, but we are using that one for our pilot's hubs (production hubs).
So, for the CGP case, I think it is just a matter to maybe have another project inside our GCP account?
Or maybe a new cluster under the existing project?
I guess since the granularity is different you could have different levels of sandboxes... a new cluster could be enough for onboarding but a more significant change maybe need a new project to test more radical changes?
Btw, who is paying the bill for our current CGP stuff? Do we have any Google contact to ask for credits for this sandbox space?

**Comment by choldgraf** [comment]
OK we have the project created and folks have access. I think the final thing to do is document this in the team compass as well as our "cloud credentials" issue

**Comment by choldgraf** [comment]
closing this one, since the account exists and we can tackle documenting it in https://github.com/2i2c-org/meta/issues/69
