### ISSUE TITLE
Proposed structure for 1-on-1 syncs

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#143]
# Summary

I had my first 1-on-1 chat with @choldgraf on Friday and I'm sure many of you will have yours upcoming if you've not had one already. During that meeting, I shared with Chris my workflow for checking in with myself on how my work is progressing and I also apply this in various other mentoring networks I'm involved in. I thought I'd share and see if this is a structure we'd like to trial within the team. This workflow is heavily inspired by Kirstie Whitaker's Lab, the full process for which, including meeting template, can be viewed here: https://github.com/WhitakerLab/Onboarding/blob/master/Setting-up-your-weekly-meetings.md

This is me sharing my workflow and proposing we try it out. I'm open to tweaks, discussions and alternative ideas - and I absolutely don't think this is the one right way to have these sorts of meetings!

(I'm going to be using the terms mentee and mentor to describe the roles in this setup, as opposed to say junior team member vs senior team member. While that is likely the dynamic that will emerge in these meetings, I also believe we are all capable of learning from one another, regardless of our levels of experience - and it's the fact that they're different that can supercharge these types of knowledge exchanges!)

### Meeting template

The meeting template involves answering the following questions (bullet points are fine!) - which you'll notice heavily overlap with our team sync! 😉 

- Who did you help this week/fortnight/...?
- Who helped you this week/fortnight/...?
- What did you achieve this week/fortnight/...?
- What did you struggle with this week/fortnight/...?
- What do you plan to work on next week/fortnight/...?
- Where do you need extra help?
- Anything other topics

This doesn't need to be stuck to rigidly, rather think of it as a way to structure your thoughts around how you've been progressing.

### Meeting structure

1. The mentee prepares their answers to the above questions ahead of the meeting
2. Mentee and mentor go through the questions with a discussion and try to solve any blockers and celebrate any achievements

In my experience, this has happened in public repositories. This provides some nice book-ending in terms of a pull request being opened before a meeting, and a pull request merged when mentor and mentee are satisfied. You can see some of my notes from meetings I have with my mentor in Kirstie's lab here: https://github.com/WhitakerLab/WhitakerLabProjectManagement/pull/510. So we could do this in the team-compass repo, or the meta repo if folks don't feel comfortable with this being entirely public.

### What about privacy / sensitive topics?

While doing this sort of team interaction in the open is inline with 2i2c's transparency as an org, it can be off-putting for individuals to bring up sensitive discussion points.

First and foremost, **the meeting will always be private** and the above template doesn't need to be stuck to rigidly. Again, it's a tool to help us structure our thoughts. Other techniques I've implemented to maintain privacy is intentionally keeping updates in the Markdown vague and using the meeting to go into greater detail.

Everyone on the team will have different risk levels for this so I'm happy to keep this open for discussion and hear alternative ideas 🙂 

# Actions

- [x] Discuss above proposal
- [x] Scope what we do and don't want these types of meetings to be
- [x] Agree on a draft 1-to-1 meeting structure
- [ ] Implement in team compass https://github.com/2i2c-org/team-compass/pull/164

**Comment by damianavila** [comment]
This is an interesting proposal! Actually, we have followed that pattern with @choldgraf in an informal way, so the template actually fits well in my case. But I think that could not be the case for others and people should feel **totally** free to adopt other structures.

Regarding the sensitive stuff: I think there is actually value to default things to private in 1:1 interactions. People could potentially feel scared to share stuff if they know things will be public, even if you try to write things in a vague way. And you also need a private place where to capture those sensitive things, so disassociating content in public and private spaces could be problematic, at a minimum.

So my first gut feeling about the proposal is to just recommend the template but avoid **any** indication of enforcement.

**Comment by yuvipanda** [comment]
This is very well thought out and helpful, thank you for opening this @sgibson91! I'd love to try this out.

**Comment by choldgraf** [comment]
> While that is likely the dynamic that will emerge in these meetings, I also believe we are all capable of learning from one another, regardless of our levels of experience - and it's the fact that they're different that can supercharge these types of knowledge exchanges

This is really excellently put :-)

In my mind, the goal of any team member is to help the team do more together than we could do alone. Mentoring others and helping them grow is a huge part of this.

I really like the structure, and am excited to step through it in our one-on-ones in the future. I like the idea of having a template regardless of whether it's posted publicly, since it'll help us think through what kinds of information is important to share with others.

re: @damianavila's suggestion - perhaps we can begin by trying to adopt this structure for our respective one-on-ones, and see how things go. In the future, we can consider adopting this as official team practice? I am not sure what are the pros and cons of making these notes be public for all - I could see arguments in both ways (if @sgibson91 has any experience with this from her time in Kirstie's group it'd be helpful to learn about!)

# Next step

Maybe a next step on this is to add the structure to the Team Compass, along with a new section describing the practice of one-on-ones. For now we don't have to mandate the structure, but offer it as a useful practice. In the future we can iterate on this in subsequent PRs/issues, and potentially make it an official team practice if need be. Does that make sense?

**Comment by damianavila** [comment]
> Does that make sense?

Makes sense to me.

**Comment by choldgraf** [comment]
hey all - I started writing some updated content for one-on-one meetings in the Team Compass, and this led to a slightly more involved PR than I was anticipating because I did some other refactoring 😬 

I'd love a review there, but either way here's the section specifically about one-on-ones: https://github.com/2i2c-org/team-compass/pull/164/files#diff-6b14132df9e5860847d73566ad05e149aeb355498e8ef0139b33abe0052018b2R16
