### ISSUE TITLE
Evaluate support service options for requests with private information

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/team-compass#151]
One of the primary characteristics of 'support' requests is that they might contain private information that should be visible to just the 2i2c engineers and the reporter. User names on the hub (if they are running into issues) is the most common piece of information that needs to be handled privately. 

This makes a purely GitHub workflow difficult, since the medium of conversation needs to move completely off github as soon as a private piece of information is shared. Often this ends up being slack or email, with fracturing problems. This is a problem even with a single private repo, since private information will be visible to other organizations with access to the same private repo.

Looking at the larger picture, IMO it is important to separate 'support' requests (conversations between 2i2c and external hub users) from issue tracking. Privacy needs to be maintained, time sensitivity is different, and triage can happen differently. No matter what we use (GitHub or otherwise), we'll need to create explicit issues out of these support tickets (I think @damianavila pointed this out during the team meeting?). We'll probably need to handle prioritization differently too, based on who is asking. 

I'd love for us to evaluate a bunch of support ticket tools (including GitHub), and form a process around that. Right now, this is just a number of us getting pinged in various slacks or gitter or Microsoft teams, and having a unified place for that would be <3

# Potential options

- GitHub Issues (private or public repositoriy)
- GitLab ([relevant docs](https://docs.gitlab.com/ee/user/project/issues/confidential_issues.html#permissions-and-access-to-confidential-issues))
- [Freshdesk](https://freshdesk.com/eu/)
- [Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
- Discourse private groups/topics ([see this thread for one guide](https://meta.discourse.org/t/discourse-as-a-private-email-support-portal/34444))

# Actions

- [x] Discuss options for support
- [x] Converge on one support service to try: we decided to use FreshDesk

**Comment by damianavila** [comment]
> This is a problem even with a single private repo, since private information will be visible to other organizations with access to the same private repo.

This is a really great point that is preventing GitHub to be our support tool candidate, IMHO.
We could have a repo for each customer but that feels hacky and a lot of work...

> I'd love for us to evaluate a bunch of support ticket tools (including GitHub), and form a process around that. Right now, this is just a number of us getting pinged in various slacks or gitter or Microsoft teams, and having a unified place for that would be <3

If we are going with another tool, that one should be our ONLY dedicated channel for support requests (to avoid these multiple pings in multiple platforms).

I guess our first task here is to come up with a list of possible candidate tools...

**Comment by yuvipanda** [comment]
> If we are going with another tool, that one should be our ONLY dedicated channel for support requests (to avoid these multiple pings in multiple platforms).

I agree.

> This is a really great point that is preventing GitHub to be our support tool candidate, IMHO.

I agree too, unfortunately

**Comment by choldgraf** [comment]
This is a great point about privacy. I asked around on Twitter, let's see if that surfaces anything

https://twitter.com/choldgraf/status/1414632656801869829?s=19

Actually one interesting response already notes that this is already possible in gitlab...

https://docs.gitlab.com/ee/user/project/issues/confidential_issues.html#permissions-and-access-to-confidential-issues

**Comment by yuvipanda** [comment]
Last time I poked around in this, I quite liked [Freshdesk](https://freshdesk.com/eu/). They seem to have [GitHub integration too](https://support.freshdesk.com/support/solutions/articles/214680-the-github-app) and weren't super expensive.

**Comment by yuvipanda** [comment]
Thinking about this some more, I would instead ask if someone is willing to trial run Freshdesk, just based on my research so far. Open to other options too!

**Comment by choldgraf** [comment]
I put a few options that I have heard about here and elsewhere in the top comment, which we can use to look into things

**Comment by damianavila** [comment]
A quick gut feeling... if we are going with a 3rd party tool, let's have a bias towards the tool specifically designed/intended to solve the "support" problem instead of tools trying to adapt to that "support" workflow into their existing (and different from support) system.

**Comment by choldgraf** [comment]
Hey all - since we need to make some progress on support right now, since @damianavila suggested we use a dedicated support service (and others have 👍 'ed it), since @yuvipanda has suggested FreshDesk as a good option, and since an hour of Googling suggests to me that FreshDesk is in-fact a reasonable choice here. How about this:

# Proposal

Let's set up a FreshDesk account for 2i2c. I can create a plan and invite others on the team to join. We set up our team support processes to use FreshDesk and improve this as we learn more about it over time. We'll define our first Support Steward as soon as FreshDesk is set up, and then try out this workflow for 2i2c support.

In 2-3 months, we should assess how things are going with FreshDesk, if we like it, if we'd want to look into other options, etc. If not, then we keep using it. If so, then we trigger a deeper research process while we continue to use FreshDesk in the interrim.

# Thoughts?

Do others agree with this as a short- and long-term plan? I think there is some downside that we haven't made "the right choice", but at the same time there's downside in not taking any action since we currently don't have much of a support structure in general. FreshDesk seems like a non-risky bet, and one that will help us build team processes around support regardless.

Curious what others think - unless somebody urges us not to do this in a day or two, I'll plan on setting up a FreshDesk account and seeing what this looks like.

**Comment by yuvipanda** [comment]
@choldgraf great plan! I fully support :D

**Comment by choldgraf** [comment]
OK I've opened up https://github.com/2i2c-org/team-compass/issues/167 to track setting up FreshDesk, so will close this one!
