### ISSUE TITLE
Create an informal / social team meeting time

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#401]
### Context

We currently have two kinds of meetings to connect with one another:

- Sprint planning meetings to quickly coordinate work
- Monthly team meetings to discuss an agenda of items

Both of these are very work-focused, and we don't have as much time for connecting with each other more informally or socially. In a recent team meeting, we agreed that it would be great to have this opportunity to connect about topics that were not work related.

### Proposal

We should define a time slot for informal (AKA, non-agenda-related team chatter). It would have a few properties:

- Optional, attendance encouraged by not required
- Short, the goal is to have quick chances to connect
- Informal, no pre-defined agenda

### Implementation guide and constraints

I'm not sure the right timing / structure for this, but wanted to open the issue so we keep track of it! Perhaps this is something others have thoughts on?

One approach is to simply define a weekly 30 minute time slot as a team "Coffee hour" (or maybe it will need to be a coffee hour for some, and a beer hour for others depending on the time zone 😅), and see how this goes.

**Comment by sgibson91** [comment]
Here's how social coffee chat is run in Whitaker Lab as an example:

* We have a slot in our calendars at 2:30pm every workday for a half hour coffee break
* 5mins before the start, a slackbot posts the zoom link to our equivalent team channel
* We have an emoji response on the slackbot message indicating who will be attending. 🚀 for attending, 🐡 for not attending. This helps avoid the situation of someone sitting in the Zoom room on their own because everyones else was too busy on that particular day.

It is not expected to attend everyday, and sometimes no one attends at all on one day. This allows for flexibility in when these social connections can happen. We only need to pick an all-round friendly _time_ and not day. People show up on the day it's convenient for them.

**Comment by choldgraf** [comment]
Ummm the blowfish emoji is amazing.

Anybody object to just trying this as-is and tweaking it over time for our needs? If so, maybe we try 8:30am California time? I feel like that is the closest thing to a time zone that might work for all. Though it'd overlap with out team meetings some days. Maybe we only have the social chat on days where we don't have team meetings?

**Comment by GeorgianaElena** [comment]
Just to make sure: the proposal is for a daily or weekly coffee/beer chat?

Also, since this will be informal and won't require being sharp or on a computer necessarily, if we don't shoot for a daily freq then I'll propose for a more friendly California time 9:30 or even 10 AM?

8AM is a harder time of day to be social than 8 PM (for me at least 😅), so if you're willing to seeing me join from my phone or during a walk in the park from time to time, then let's have this informal chat later in the evening/morning 🌼 🍻 ☕  

What do you think?

**Comment by choldgraf** [comment]
My preference is "more often than weekly" but I'm fine if it is also "less often than daily". Given we are a small team, going as frequently as daily might make it less-likely to have people join at the same time. Want to just propose a frequency and we can try this out for a bit?

Another question: is this **just for the 2i2c team** or can we advertise it more generally in `#general`?

**Comment by sgibson91** [comment]
> join from my phone or during a walk in the park from time to time

People definitely do this from time-to-time in the Whitaker Lab - it's supposed to be informal

> Another question: is this just for the 2i2c team or can we advertise it more generally in #general?

My question to this would be: what's the objective? To bond the engineering team or something else? If we're going to make it a "no shop talk" space, it needs to be safe enough for people to share things not related to work. I'm not saying that would be the case if we opened it up to `#general` too but maybe its something we should work towards rather than starting with?

**Comment by damianavila** [comment]
> My preference is "more often than weekly" but I'm fine if it is also "less often than daily".

I agree... maybe we start on a weekly basis and then make more frequent as demand increases?

> My question to this would be: what's the objective? To bond the engineering team or something else? If we're going to make it a "no shop talk" space, it needs to be safe enough for people to share things not related to work. I'm not saying that would be the case if we opened it up to #general too but maybe its something we should work towards rather than starting with?

I think we should focus on our team first in a private/secure space. IMHO, "To bond the engineering team" should be the first goal here.

**Comment by damianavila** [comment]
This is a really good point and since you already have experience with this pattern, I will follow you here 😉!

**Comment by choldgraf** [comment]
Agree with Sarah's points above!

### proposal

How about this:

- time: 9:30am us/Pacific 
- frequency: every Monday, Wednesday, Friday
- format: no structure, no expectations about phone vs zoom, try not to talk about work 🙃
- people: our team - anyone with access to #team-updates
- attendance: totally optional, if nobody shows up that is fine
- notification: use a slack notification in #team-updates, ask team members to emoji respond with 🌈 if they'll attend, 🐡 if they will not.
- plan: pilot this for 3 months and see how it goes


Does that work for folks? Anybody want to suggest edits?

**Comment by sgibson91** [comment]
I took the liberty of adding the social coffee chat to the Team calendar and setting reminders in the team-updates channel starting from next week 🚀

**Comment by damianavila** [comment]
Thanks, @sgibson91!
Let's close this one after we have the first one done 😉
