### ISSUE TITLE
[blog] Crowdsource a Quarter 3 Community Update

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#515]
### Summary / idea for post

Quarter 3 is almost over, and so it is time for us to update communities with what we have accomplished and learned over the last several months. I tried and failed to do this last quarter (https://github.com/2i2c-org/team-compass/issues/452), so I wonder if we can  take a different approach to things this time around.

### Content from each team please!

Can we collaboratively create this blog post together, by sourcing the major accomplishments from each of our teams? For now, I think we can define those teams as @2i2c-org/tech-team , @2i2c-org/partnerships-and-community-guidance , and @2i2c-org/organization-wide .

Here's a HackMD where I've got a blog post draft:

- [**HackMD draft post**](https://hackmd.io/FL2hxXoJRCyIEETP1E3sOg)

Some suggestions:

- The biggest accomplishments within your group, and why they're important
- The most important things you learned
- The most-notable _upstream contributions_ that happened as part of this
- Anything else you think is important to share with others.

Provide enough information so that a person with relatively little context can understand what you're talking about and why it's useful.

### Checkpoints

- [ ] ~2022-10-05: Crowdsource content from our team as comments in this issue~
- [x] 2022-10-14: Draft of post ready for review
- [x] https://github.com/2i2c-org/2i2c-org.github.io/pull/117
- [ ] Send out tweets and LinkedIn
- [ ] Send to 2i2c listserv

**Comment by choldgraf** [comment]
### Update: updated checkpoint date and structure above

I didn't have time to keep track of this one because of all the conference travel, so let's bump the checkpoint date a little bit. I've also simplified the prompts a little bit to keep things simple for our first iteration. Can @damianavila and @jmunroe and @colliand please lead efforts to fill out their respective sections above? I'll do the same as well

**Comment by damianavila** [comment]
@choldgraf, can you update the checkpoint date here since the current one is no longer relevant?

**Comment by choldgraf** [comment]
Good point - I've updated the date to Friday, when I'd like to have a draft ready for review, with or without input from others.

**Comment by damianavila** [comment]
@choldgraf, hopefully, this is useful...
I tried to collect the most relevant Eng-related pieces in sections I have already seen in your draft.

# New hubs
* [New Hub] PaleoCube and PaleoHack hubs: https://github.com/2i2c-org/infrastructure/issues/1418
* [New Hub] NeuroHackademy 2022: https://github.com/2i2c-org/infrastructure/issues/1505
* [New Hub] Alabama Water Institute CIROH hub: https://github.com/2i2c-org/infrastructure/issues/1444
* [New Hub] OceanHackWeek 2022: https://github.com/2i2c-org/infrastructure/issues/1515
* [New Hub] COESSING Pangeo-Style Hub: https://github.com/2i2c-org/infrastructure/issues/1516
* [New Hub] Temple University Education Hub: https://github.com/2i2c-org/infrastructure/issues/1648
* [New Hub] Callysto Hub: https://github.com/2i2c-org/infrastructure/issues/1439
* [New Hub] London Interdisciplinary School: https://github.com/2i2c-org/infrastructure/issues/1485

# Events
* [EVENT] NeuroHackademy 2022: https://github.com/2i2c-org/infrastructure/issues/1300
* [EVENT] OceanHackWeek 2022: https://github.com/2i2c-org/infrastructure/issues/1576
* [EVENT] Allen Institute Summer Workshop on the Dynamic Brain: https://github.com/2i2c-org/infrastructure/issues/1621

# Features
* Authenticated and optionally private static websites served from a hub: https://github.com/2i2c-org/infrastructure/issues/1500 and https://github.com/2i2c-org/infrastructure/pull/1502
* Design a secure method to receive secret keys: https://github.com/2i2c-org/infrastructure/issues/639
* Allow access to multiple s3 buckets from the hub: https://github.com/2i2c-org/infrastructure/issues/1455

# Improvements and fixes
* Document the central Grafana: https://github.com/2i2c-org/infrastructure/issues/1438
* Enable choosing an environment for each profile: https://github.com/2i2c-org/infrastructure/issues/1640
* Templates sync bug fixes: https://github.com/2i2c-org/infrastructure/issues/1695
* Document how to access and modify a user's filesystem: https://github.com/2i2c-org/infrastructure/issues/1691
* Document the workflow to post a deployment plan to a PR and Restructure CI/CD section: https://github.com/2i2c-org/infrastructure/pull/1535
* Split up Authentication docs into individual providers: https://github.com/2i2c-org/infrastructure/pull/1586
* Centralize the initContainer that fixes ownership: https://github.com/2i2c-org/infrastructure/pull/1591
* Replace GitHub with PagerDuty in our Incident Response process: https://github.com/2i2c-org/team-compass/pull/508 (this was technically closed in Oct but most of the work was actually performed during September time).

# In-progress work (not sure if we should mention it since we are talking about accomplished things whereas there was some work already done on these projects)
* Pangeo/Columbia potentially joining the mybinder.org federation with an AWS deployment: https://github.com/2i2c-org/infrastructure/issues/919#issuecomment-1258130800
* Exploratory phase to develop an r2d JHub service: https://github.com/2i2c-org/infrastructure/issues/1382#issuecomment-1200292090

# Not Eng (but relevant, IMHO)
* Update our Hiring and Candidate Search documentation: https://github.com/2i2c-org/team-compass/issues/436
* Decide on an immediate pricing model for cloud cost pass-through: https://github.com/2i2c-org/meta/issues/147

**Comment by jmunroe** [comment]
I love the highlighting of all of the new hubs and events that have occured.  From a @2i2c-org/partnerships-and-community-guidance point of view, should we be including a invitation to reach out to us if you like to your community to have their own hub?  Potentially:

> If your education or research community is interested having their own managed JupyterHub, please contact us at partnerships@2i2c.org. We have a shared clusters already deployed on Google Cloud Platform on `us-central1-b` and `europe-west2` and we will soon deploy a shared cluster on Amazon Web Services on `us-west-2`.  Dedicated clusters can be run on any major cloud provider. Please see <LINK TO SERVICE OFFERING GDOC> for more details.

We also should have a section advertising our new engineering position.

I'll add these to the HackMD.

**Comment by choldgraf** [comment]
I've got a blog post draft up here, let's take conversation over there: https://github.com/2i2c-org/2i2c-org.github.io/pull/117

My plan is to post this on Friday of this week, unless somebody suggests a different date.
