### ISSUE TITLE
Receipts for Ramp emailed to `receipts@2i2c.org` or `receipts@ramp.com`?

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/team-compass#800]
My understanding was to send this receipt to `receipts@2i2c.org` which then would be manually emailed to `receipts@ramp.com`.  

I see that the Team Compass (https://team-compass.2i2c.org/administration/reimburse/#reimbursements-and-ramp) is unclear on this matter and does not explicitly mention `receipts@2i2c.org` as the method to follow for those without admin privileges on ramp.

_Originally posted by @jmunroe in https://github.com/2i2c-org/community-showcase/issues/64#issuecomment-1927503374_

**Comment by choldgraf** [comment]
Thanks for clarifying here - I've actually been prototyping a process with Camille so that we can have a single e-mailable place for receipts and don't require team members to get their own ramp accounts just to get reimbursed.

Here's the process to follow, and we can use the text below to put into the Team Compass when we have a moment:

1. Purchase something with the 2i2c credit card.
2. E-mail the receipt to `receipts@2i2c.org`. This is a "google group" we use to aggregate receipts.
3. Every week, Camille will check Ramp and look for any items that are missing receipts. She will match them to the respective item in Ramp.com
4. For any that are not clear, Camille will follow up with the person she thinks is suited to help clarify.
