### ISSUE TITLE
Feedback on draft proposal for "Operations" board

### ISSUE THREAD

**Issue by aprilmj** [2i2c-org/team-compass#819]
This is a proposal for a new delivery board (also called a sprint board) for "Operations". The Operations board will be used to plan and track task-level work across the organization, including overhead of running the org and managing people - things that aren't owned by Partnerships and/or Engineering. 

### Questions for feedback:
1. Does the language in this proposal makes sense?
2. Is "Operations" the right label for this board (we currently use "Operations" as a name for a functional area that includes grants, organization-wide change, and other projects - is it ok to extend that to People and Product tasks)?
3. Should the Operations sprint cadence be fortnightly (following the pattern established by Partnerships and Engineering) or monthly (due to what we assume will be larger, longer-running tasks)?
4. Who should be the initial Operations team? (proposed answer: the `#solutions-forum` team (whose name will change to "Initiatives")
5. Is this proposal safe to try?
6. Please edit this top comment with any language changes/corrections. 

**What is "Operations"?**
This is a catch-all term for work that comes from different sources and functional areas but requires either cross-team  or operational team (ED, Partnerships, Chief of Staff, People) action. We could also define this category as what it is not - it's work not owned by Engineering. :) 

**What is a "task"?**
Tasks are discrete pieces of work, tracked as GitHub issues, that can be completed by an assigned collection of people within an agreed period (proposal: we start with 2 weeks as that agreed period, with an expectation that it shifts to monthly).

**Why do we need a sprint board and delivery process for this stuff?**
There are several anti-patterns that emerge when we don't intentionally manage this organization-wide work at a detailed level: 
- We start many things and finish none
- Work we need to do is less discoverable or even lost
- It's not clear what needs review when 
- It's not clear who to ask for input or when
- It's hard to identify when work is blocked

Conversely, when we do have a process for managing work, we can visualize what's in flight, team members are more aware of what they need to contribute to, and we're able to agree on what's most important at a given time. 

### The lifecycle of an Operations task
1. Following the prioritization of initiatives on the **Initiatives Board** (described in #817), any initiative we agree to work on is broken down into tasks
2. The Initiatives team, which includes representation from ED/Chief of Staff, People, Product, Engineering and Partnerships, meets fortnightly to agree on tasks to complete in the next fortnight, and moves those tasks to the **Operations Sprint/Delivery Board** 
3. A member of the Operations team takes initial ownership (by self-assigning the issue in GitHub) and adds other needed collaborators from any team (by assigning them to the issue in GitHub)
4. All assigned team members take responsibility for providing input or review as requested (this is why we need cross-team representation in the planning discussion - we need to know we aren't overloading other teams with ops work!), but the initial owner serves as the coordinator
5. As needed, we use the **Initiatives Slack channel** to signal boost and conduct ad hoc discussions about tasks on the Operations board (agreed in comments that we don't need a new Slack channel for this purpose)
6. When tasks are complete, the issues are closed in GitHub
7. The Initiatives team reflects and retrospects at the end of the fortnightly cycle

**Comment by choldgraf** [comment]
My 2 cents: I think that this proposal is safe-to-try as-is, and that we can answer some of the outstanding questions if we had a prototype board to start working with. I think it'll be easier to gain intuition for the "right way" to use the board if we have something to use.

So what do you think about:

1. Create an Operations board
2. Say that the `#solution-forum` team have responsibility for checking this board
3. Use the definitions of "what is a task" and "lifecycle" defined here as a starting point, while recognizing we don't yet know what kind of "iteration" to use.

And see how that goes just as a starting point. We could then revisit the open questions in 2-4 weeks once we've had some time to see how the process plays out.

**Comment by haroldcampbell** [comment]
In broad strokes, I'm also in agreement that this is safe-to-try. I would add the following change however, instead of creating a new **Operations Slack** channel, simply use the `#solution-forum` channel. If it then becomes a chore or there is too much noise in the `#solution-forum` channel, then we create the **#operations** channel.

My thinking is that we just agreed to delete `#cross-functinal-initiatives` channel because the members of the solution-forum found that it wasn't valuable and was confusing.

_Note: This isn't a blocking change for me._

Otherwise, thumbs up from me.

**Comment by aprilmj** [comment]
I'd also be ok with changing this so the `#solution-forum` Slack channel (or, if we choose to rename that to `#initiatives` whatever the new name is) is the channel for the Ops board. I don't think the Ops process will add a huge amount of traffic to the channel.

**Comment by choldgraf** [comment]
Sounds good to me, always a fan of "fewer things until we agree we need to create new things") 👍

**Comment by Gman0909** [comment]
I'm still not entirely sure why we couldn't just use the existing Initiatives board for this purpose, but I am not opposed to the idea. We'll see soon enough whether this addition is a net positive to our process. I also second re-purposing the #solution-forum channel.

**Comment by jmunroe** [comment]
I think what is being described above is already pretty consistent with what is currently serving as the 'partnerships board'.

I don't see any fundamental difference between partnerships and other 'operations' level work. The key point is to have on this board task-level issues that are completable within a two-week iteration. 2i2c is not yet large enough to justify a many independent teams.

Within partnerships, we have been doing biweekly planning and retrospective meetings but doing that with only three people in partnerships I think it would be better to include more people in the process.

My proposal is rename the 'partnerships' board as an 'operations' or a 'business' board.

**Comment by choldgraf** [comment]
> My proposal is rename the 'partnerships' board as an 'operations' or a 'business' board.

To make sure I understand the proposal, it is basically that we have 3 boards that drive our work:

1. Initiatives: Tracks our high-level goals, and complex projects that make significant progress towards those goals.
2. Operations: A team-wide board focused around delivery, with some way to denote team responsibility on it. Includes all organizational tasks/actions except for Engineering ones.
3. Engineering: A "special case" of the Operations board. It is functionally the same but focused on tech development cycles and largely attended to by the engineering team.

If so, I think this is a nice idea. A few reasons why:

- It does not grow the number of boards, because we already have a partnerships board.
- It gives us only 2 classes of boards that drive work (and potentially a third type of board to manage projects, based on how https://github.com/2i2c-org/team-compass/issues/820 goes)
- It mimics the fact that we identified the engineering team as "a uniquely complex team and workflow system" in the sense that we decided the engineering team needed their own delivery manager.
- It gives us an extension point to create a new dedicated board if one sub-team's work becomes so complex that it is swamping our "operations" board
- Conversely, it might be a step towards having a single shared delivery board if we instead want to move in that direction in the future.

Question:

- Would the `operations` board come with the `#partnerships` rituals (sprint meetings etc) or would we have multiple teams with their own rituals that just use the same board?

**Comment by jmunroe** [comment]
That's a great summary of the proposal. 

Yes, there would be only one biweekly planning and one retrospective ritual for an operations board under this proposal.

In terms of flight levels, the initiatives board is at level 2 (coordination) and the operations and engineering boards are at level 1 (delivery).

**Comment by aprilmj** [comment]
I love the suggestion of consolidating "Operations" and Partnerships into a single biweekly board and process cycle - it's fewer boards (WOO!), but more importantly I suspect we can have much more complete, cross-functional conversations (which is really why we do these boards & processes - so we know what's happening and get more done).

**Comment by choldgraf** [comment]
OK thanks all for this feedback! I think at this point it would be most helpful to converge on some language that we can start with. I wrote up a short PR at the link below and will use that for discussion from here on:

- https://github.com/2i2c-org/team-compass/pull/821

**Comment by haroldcampbell** [comment]
Happiness!
