### ISSUE TITLE
Add community (formerly "upstream") projects to the Initiatives planning process

### ISSUE THREAD

**Issue by aprilmj** [2i2c-org/team-compass#829]
### Context

This issue tracks the implementation of #820 (proposal for including upstream work in initiatives and delivery planning). 

### Updates and actions
We want to have an initiative on the Initiatives Board for all upstream projects/contributions that 2i2c people are working on collectively. For now, that means making sure everything on this list is tracked as an initiative: 

#### Grants 
- [x] https://github.com/2i2c-org/meta/issues/805
- [x] https://github.com/2i2c-org/meta/issues/790
- [x] https://github.com/2i2c-org/meta/issues/789
- [x] https://github.com/2i2c-org/meta/issues/803
- [x] https://github.com/2i2c-org/meta/issues/787
- [x] https://github.com/2i2c-org/meta/issues/788

#### Pending grants
- [x] https://github.com/2i2c-org/leads/issues/300
- [x] https://github.com/2i2c-org/leads/issues/309
- [x] https://github.com/2i2c-org/leads/issues/308 (NOI submitted)
- [x] https://github.com/2i2c-org/leads/issues/297 

### Potential grants?
- [x] https://github.com/2i2c-org/leads/issues/313
- [x] https://github.com/2i2c-org/leads/issues/324

#### Major community partnerships
- [x] https://github.com/2i2c-org/leads/issues/320
- [x] https://github.com/2i2c-org/leads/issues/307
- [x] https://github.com/2i2c-org/leads/issues/130 

Once added, we'll also need to 
- [x] Incorporate these initiatives into our next round of initiative-level planning (requires someone knowledgeable to do some refinement/prep of the initiative)
- [x] Add delivery-level tasks for the upstream initiatives we prioritize to the next round of Engineering & Operations sprint planning

**Comment by choldgraf** [comment]
Just looking at the list that's here and wanted to share a general thought (non-blocking on this issue, but if it's important to discuss now I'm happy to do so).

I suspect that we'll have to grapple with the question of "how to introduce a WIP limit given that we have 9 upstream/external initiatives". I don't think we're there yet, but eventually we'll want to limit the total number of in-flight initiatives so that we're not doing too much at the same time.

We might also want to define our _own_ initiatives that feed into multiple upstream projects (e.g. "identify a thing that 4 projects want, and create an initiative that will check "done" boxes in multiple projects when it is complete)

**Comment by aprilmj** [comment]
@choldgraf Good questions! I suggest capturing the list first, then asking ourselves what's possible or reasonable when we're planning. 9 is a lot of initiatives to have in progress, if people are actively contributing to all of them! 

How do y'all identify and track work that serves multiple communities' needs today?

**Comment by consideRatio** [comment]
When I think about "upstream", I believe what I'm thinking of is open source projects used by several separate parties that 2i2c or our communities depend on. In this, I'd list for example jupyterlab, jupyter_server, jupyterhub, dask, ipywidgets, nbgitpuller, grafana, etc.

Is perhaps "community projects" a better fit of how to speak about these than "upstream projects"?

**Comment by aprilmj** [comment]
Nice suggestion @consideRatio! It started as "upstream leadership", but I like "community" better as a category.

**Comment by choldgraf** [comment]
+1 to that terminology as well, thanks for thinking it through @consideRatio 

Also is a more inclusive terminology, since something like Jupyter For Health is more like a "community (we are serving) project" rather than a "community (we use technology from) project". I'd classify the latter as "upstream", but not the former. So "Community projects" feels like it captures both.

**Comment by jmunroe** [comment]
> 9 is a lot of initiatives to have in progress, if people are actively contributing to all of them!

This tells me we need a way to distinguish between an initiative which is work-in-process for the 2i2c team as distinct from a project that is longer lived and may have significant periods of time that do not require active participation from 2i2c.  An objective of the the initiatives board to me is to capture the initiatives we already have as work-in-process and use that to decide if we have capacity to start work on a new initiatives.

There is a longish list of project and communities that we provide support for, we have received money for, we need to be able to assist with when called upon, but are not 'initiatives' in the sense of something we are intentional about allocating our resources towards.  There are also upstream projects that we are also highly involved with (jupyterlab, jupyter_server, jupyterhub, dask, ipywidgets, nbgitpuller, ...) but none of those 'projects' can ever be considered "done" so I am not sure how to represent them as initiatives.

I agree that this is best figured out by adding some 'initiatives' to this board and using them as specific examples of what we are taking about.  

For example, I am at this moment looking 'Project Pythia'. That 'project' is long-lived and hopefully will continue far into the future with or without 2i2c direct involvement. So 'Project Pythia' is not a 2i2c initiative.  We are co-investigators on an NSF OSE GEO grant to fund and support 'Project Pythia'. The grant lasts three years and not all of the deliverables under the grant dependent only on 2i2c.  The grant is not an 'initiative' of 2i2c either.  (If it was, it will sit on this board for three years as WIP -- I don't think that is useful).  There are some particular deliverables (some explicit and some implicit) for 2i2c under the Project Pythia grant:
- monthly participation by at PI and community meetings
- annual summer hackathon (both participation in the event and engineering support for the event)
- maintaining and deploying 'binder'-like system for Project Pythia cookbooks on a GCP
- improving and contributing to the CI/CD workflows regarding Project Pythia cookbooks
- developing new capacity on OpenStack systems like Jetstream2 for deploying and maintain infrastructure
- contributing to cookbooks
- contributing to the data engineering around cookbooks
- connecting other communities partnerships with the Project Pythia project

This is not a comprehensive list but some of things rattling around in my brain under the concept 'Project Pythia' that I could see being adopted as initiatives for 2i2c. There is a much longer list of deliverables for other project partners on this grant.

Some of those 'initiatives' are more refined and ready for action. Others are require refinement.  Are these the kind of the 'initiatives' we should be putting on this board?

**Comment by jmunroe** [comment]
I've updated the top comment to group different types of community projects by 'type'. The list of types is not complete or finalized.

**Comment by aprilmj** [comment]
Closing this issue with an assumption that we can revisit the entire initiatives planning process post-July and will be working differently until then.
